/* Modelagem Básica -

ENTIDADE=TABELA
CAMPOS=ATRIBUTOS */

CLIENTE

NOME - CARACTER(30)
CPF - NUMERICO(11)
EMAIL - CARACTER(30)
TELEFONE - CARACTER(30)
ENDERECO - CARACTER(100)
SEXO - CARACTER(1)

/* PROCESSO DE MODELAGEM */
/*FASE 01 E FASE 02 - AD ADM DE DADOS */

MODELAGEM CONCEITUAL - RASCUNHO
MODELAGEM LÓGICA - QUALQUER PROGRAMA DE MODELAGEM

/* FASE 03 - DBA / AD */

MODELAGEM FÍSICA - SCRIPTS DE BANCO

/* INICIANDO A MODELAGEM FÍSICA */
/* CRIANDO O BANCO DE DADOS */

CREATE DATABASE EXEMPLO 
CREATE DATABASE PROJETO;

/* CONECTANDO-SE AO BANCO */

USE PROJETO;

/* CRIANDO A TABELA DO CLIENTE */

CREATE TABLE CLIENTE(
	NOME VARCHAR(30),
	SEXO CHAR(1),
	EMAIL VARCHAR(30),
	CPF INT(11),
	TELEFONE VARCHAR(30),
	ENDERECO VARCHAR(100)
);

/* VERIFICANDO AS TABELAS DO BANCO */

SHOW TABLES;
USE EXEMPLO;
SHOW TABLES;
USE PROJETO;

/*DECOBRINDO COM É A ESTRUTURA DE UM TABELA */

DESC CLIENTE;

-----

/* TIPOS DE DADOS 
TODOS OS BANCO DE DADOS POSSUEM TIPOS QUE DEVEM SER ATRIBUIDO AOS DADOS DE UMA TABELA. 
PARA CARACTERES LITERAIS, TEMOS CHA E VARCHAR, PARA NUMEROS TEMOS INT E FLOAT, PARA OBJETOS COMO FOTO E DOCUMENTOS TEMOS O BLOB, PARA TEXTO EXTENSOS, TEMOS TEXT. 
A DICIPLINA DE BANCO DE DAODS E TAO FANTASTICA QUE AO ENTENDERMOS O PORQUE DAS COISAS, PODEMOS INICIAR JA EM MODO AVANÇADO E UM BOM EXEMPLO DISSO SAO OS TIPOS. 
HA UMA PROFISSAO DENTRO DA AREA QUE E A DO ANALISTA DE PERFORMANCE OU TUNING, ESSE PROFICIONAL E RESPONSAVEL POR ANALISAR O BANCO DE DADOS E DEIXA-LO MAIS RAPIDO. PARECE ALGO AVANÇADO, E E POREM, COM ALGUMAS ATITUDES SIMPLES, PODEMOS DEIXAR O BANCO SEM A NECESSIDADE DE ATUAÇAO DESSE PROFISSIONAL. 
CADA CARACTER NO BANCO DE DADOS, VALE 1 BYTE.
SENDO ASSIM, SE EU ENTRO COM O JOAO ESTOU ENTRANDO COM 4 BYTES NO MEU BANCO.
E O QUE ISSO TEM A VER COM A TIAGEM DE TABELAS?
O BANCO DE DADOS FUNCIONA COMO UM DOWNLOAD DE DADOS DA INTERNET.
SE BAIXARMOS UM ARQUIVO DE 1 GIGA, TEMOS UM TEMPO MAIOR QUE O DOWNLOAD DE 50 MEGAS, CONSIDERANDO A MESMA VELOCIDADE DE CONEXAO. AO TIPARMOS UM TABELA DE MODO ERRADO OU DISPLICENTE, VAMOS AUMENTAR A QUANTIDADES DE DADOS QUE SERA BAIXADA DO BANCO DE DADOS, PROLONGANDO ASSIM O TEMPO DE RESPOSTA.
UMA COMPARACAO BEM DIDATICA E O TIPO CHAR E VARCHAR.
A PALAVRA VAR, VEM DE VARIANT, EM INGLES, OU SEJA QUE E DINAMICA.
LOGO VIMOS QUE 1 CARACTER E IGUAL A 1 BYTE.
VEJAMOS ENTAO A TIPAGEM

VARCHAR(10)
CHAR(10)

ENTRANDO A PALAVRA JOAO
TOTAL DE BYTES VARCHAR(10)=4 BYTES
TOTAL DE BYTES CHAR(10)=10 BYTES

ISSO OCORRE POIS O CHAR NAO VARIA.
OS CARACTERES RESTANTE SERAO PREENCHIDOS COM ESPAÇO.
ELES NAO FICAO VAZIOS.
ENQUANTO QUE NO VARCHAR, O TIPO VARIA CONFORME O DADO.
ENTAO UTILIZAMOS SEMPRE O VARCHAR? NAO.
OCHARE LIGEIRAMENTE MAIS PERFORMATICO, POR NAO TER QUE GASTAR TEMPO VARIANDO DE TAMANHO. 
ENTAO A REGRA E UTILIZAR SEMPRE O CHAR QUANDO SABEMOS QUE O NUMERO DE CARACTERES NAQUELA COLUNA NAO VAI VARIAR NUNCA. 
POR EXEMPLO, UNIDADES FEDERATIVAS, COMO DOIS DIGITOS, SEXO COM 1 DIGITO E ASSIM POR DIANTE.
VISTA A DIFERNÇA QUE PODEMOS FAZER COM UMA TIPAGEM CORRETA DE TABELAS, NA PROXIMA AULA DETALHAREMOS OS TIPOS DO MYSQL E NOS MODULOS ESPECIFICOS DE CADA BANCO, VOCE ENTENDERA OS TIPOS DE CADA BANCO, VOCE ENTENDERA OS TIPOS CORRESPONDENTES NO SQL SERVER E NO ORACLE, QUE MUDAM MUITO POUCI. */

/* INSERINDO DADOS E VALORES NULOS */

USE PROJETO;

/* MOSTRA AS TABELAS */

SHOW TABLES;

/* EXIBINDO A EXTRUTURA DE UMA TABELA */

DESC CLIENTE;

/* SINTAXE BASICA DE INSERÇAO - INSERT INTO TABELA...*/
/* FORMA 01 - OMINTINDO AS COLUNAS */

INSERT INTO CLIENTE VALUES('JOAO','M','JOAO@GMAIL.COM',485248625,'78561863','MAIA LACERDA - ESTACIO - RIO DE JANEIRO -RJ');

INSERT INTO CLIENTE VALUES('CELIA','F','CELIA@GMAIL.COM',567281575,'28578921','RIACHUELO - CENTRO - RIO DE JANEIRO - RJ');

INSERT INTO CLIENTE VALUES('JORGE','M',NULL,218623868,'26878468','OSCAR CURY - BOM RETIRO - PATOS DE MINAS - MG');

/* FORMA 02 - COLOCANDO AS COLUNAS */

INSERT INTO CLIENTE(NOME,SEXO,ENDERECO,TELEFONE,CPF) VALUES('LILIAN','F','SENADOR SOARES - TIJUCA - RIO DE JANEIRO RJ','28517966',235885175);

/* FORMA 03 - INSERINDO CAMPOS - SOMENTE MYSQL */

INSERT INTO CLIENTE VALUES('ANA','F','ANA@GLOBO.COM',274924586,'46174862','PRES ANTONIO CARLOS - CENTRO - SAO PAULO - SP'),
			  ('CARLA','F','CARLOS@TERATI.COM',942576282,'564856312','SAMUEL SILVA -CENTRO -BELO HORIZONTE -MG');

INSERT INTO CLIENTE(NOME,SEXO,ENDERECO,TELEFONE,CPF) VALUES('CLARA','F','SENADOR SOARES - TIJUCA RIO DE JANEIRO - RJ','85474562',785127663);

INSERT INTO CLIENTE(NOME,SEXO,ENDERECO,TELEFONE,CPF) VALUES('CLARA','F','SENADOR SOARES - TIJUCA - RIO DE JANEIRO - RJ','812189248',46841534);

/* O CAMPO SELECT 
SELECAO PROJECAO E JUNCAO */

SELECT NOW() AS DATA_HORA, 'FELIPE MAFRA' AS PROFESSOR;

SELECT 'FELIPE MAFRA';

SELECT 'BANCO DE DADOS';

/* ALIAS DE COLUNAS */

SELECT NOME AS CLIENTE, SEXO, EMAIL FROM CLIENTE;

SELECT NOME, SEXO, EMAIL, ENDERECO FROM CLIENTE;

SELECT EMAIL, SEXO, ENDERECO, NOME FROM CLIENTE;

SELECT EMAIL, SEXO, ENDERECO, NOME, NOW() AS DATA_HORA FROM CLIENTE;

/* APENAS PARA FINS ACADEMICOS */

SELECT * FROM CLIENTE;

/* FILTRANDO DADOS COM WHERE E LIKE */

SELECT NOME, TELEFONE FROM CLIENTE;

/* FILTRANDO */

SELECT NOME, SEXO FROM CLIENTE WHERE SEXO = 'M';

SELECT NOME, ENDERECO FROM CLIENTE WHERE SEXO = 'F';

SELECT NOME, SEXO FROM CLIENTE WHERE ENDERECO = 'RJ';

/* UTILIZANDO O LIKE */

SELECT NOME, SEXO FROM CLIENTE WHERE ENDERECO LIKE = 'RJ';

/* CARACTER CORINGA % -> QUALQUER COISA */

SELECT NOME, SEXO FROM CLIENTE WHERE ENDERECO LIKE '%RJ';

SELECT NOME, SEXO, ENDERECO FROM CLIENTE WHERE ENDERECO LIKE '%RJ';

SELECT NOME, SEXO, ENDERECO FROM CLIENTE WHERE ENDERECO LIKE 'OSCAR CURY%';

SELECT NOME, SEXO, ENDERECO FROM CLIENTE WHERE ENDERECO LIKE '%CENTRO%';

/* RESOVENDO O EXERCICIO */

CREATE DATABASE LIVRARIA;

USE LIVRARIA;

CREATE TABLE LIVROS(
	LIVRO VARCHAR(100),
	AUTOR VARCHAR(100),
	SEXO CHAR(1),
	PAGINAS CHAR(5),
	EDITORA VARCHAR(30),
	VALOR FLOAT(10,2),
	UF CHAR(2),
	ANO CHAR(4)
);

/*VERIFICANDO OS BANCOS */

SHOW DATABASES;

/* CONECTANDO A UM BANCO */

USE LIVRARIA;

INSERT INTO LIVROS 
VALUES('CAVALEIRO REAL','ANA CLAUDIA','F','465','ATLAS',46.9,'RJ','2009');
INSERT INTO LIVROS 
VALUES('SQL PARA LEIGOS','JOAO NUNES','M','450','ADDISON',98,'SP','2018');
INSERT INTO LIVROS 
VALUES('RECEITAS CASEIRAS','CELIA TAVARES','F','210','ATLAS',45,'RJ','2008');
INSERT INTO LIVROS 
VALUES('PESSOAS EFETIVAS','EDUARDO SANTOS','M','390','BETA',78.99,'RJ','2018');
INSERT INTO LIVROS 
VALUES('HABITOS SAUDAVES','EDUARDO SANTOS','M','630','BETA',150.98,'RJ','2019');
INSERT INTO LIVROS 
VALUES('A CASA MARROM','HERMES MACEDO','M','250','BUBBA',60,'MG','2016');
INSERT INTO LIVROS 
VALUES('ESTACIO QUERIDO','GERALDO FRANCISCO','M','310','INSIGNIA',100,'ES','2015');
INSERT INTO LIVROS 
VALUES('PRA SEMPRE AMIGOS','LEDA SILVA','F','510','INSIGNIA',78.98,'ES','2011');
INSERT INTO LIVROS 
VALUES('COPOS INESQUECIVES','MARCOS ALCATRA','M','200','LARSON',130.98,'RS','2018');
INSERT INTO LIVROS 
VALUES('O PODER DA MENTE','CLARA MAFRA','F','120','CONTINENTAL',56.58,'RS','2017');

/* 1 - TRAZER TODOS OS DADOS. */

SELECT * FROM LIVROS;

/* 2 - TRAZER O NOME DO LIVRO E DO EDITORA */

SELECT LIVRO, EDITORA FROM LIVROS;

/* 3 - TRAZER O NOME DO LIVRO E A UF DOS LIVROS PUBLICADOS POR AUTORES DO SEXO MARCULINO. */ 

SELECT LIVRO, UF FROM LIVROS WHERE SEXO = 'M';

SELECT AUTOR, SEXO, LIVRO, UF FROM LIVROS WHERE SEXO = 'M';

/* 4 - TRAZER NOME DE LIVROS E NUMERO DE PAGINAS DO LIVROS PUBLICADOS POR AUTORE DO SEXO FEMININO. */

SELECT LIVRO, PAGINAS FROM LIVROS WHERE SEXO = 'F';

SELECT AUTOR, LIVRO, PAGINAS FROM LIVROS WHERE SEXO = 'F';

/* 5 - TRAZER OS VALORES DOS LIVROS DAS EDITORAS DE SAO PAULO. */

SELECT LIVRO, VALOR FROM LIVROS WHERE UF = 'SP';

SELECT UF, LIVRO, VALOR FROM LIVROS WHERE UF = 'SP';

/* 6 - TRAZER OS DADOS DOS AUTORES DO SEXO MASCULINO QUE TIVERAM LIVROS PUBLICADOS POR SAO PAULO OU RIO DE JANEIRO */

SELECT AUTOR, SEXO, UF FROM LIVROS WHERE SEXO = 'M' AND UF = 'SP' OR UF = 'RJ';

SELECT AUTOR, SEXO, UF FROM LIVROS WHERE SEXO = 'M' AND (UF = 'SP' OR UF = 'RJ');

SELECT AUTOR, SEXO, UF FROM LIVROS WHERE SEXO = 'M' AND UF = 'SP' AND PAGINAS > 100;

/* OPERADOR LOGICO OR -> PARA QUE A SAIDA DA QUERY SEJA VERDADEIRA, BASTA QUE APENAS UMA CONDICAO SEJA VERDADEIRA.
AND -> PARA QUE A SAIDA SEJA VERDADEIRA TODAS AS CONDICOES PRECISA SER VERDADEIRAS. */

/* OR - OU */

SHOW DATABASES;

USE PROJETO;

SELECT * FROM CLIENTE;

SELECT NOME, SEXO, ENDERECO FROM CLIENTE WHERE SEXO = 'M' OR ENDERECO LIKE '%RJ';

SELECT NOME, SEXO, ENDERECO FROM CLIENTE WHERE SEXO = 'M' AND ENDERECO LIKE '%RJ';

SELECT NOME, SEXO, ENDERECO FROM CLIENTE WHERE SEXO = 'F' OR ENDERECO LIKE '%ESTACIO';

/* AND - E */

SELECT NOME, SEXO, ENDERECO FROM CLIENTE WHERE SEXO = 'M' AND ENDERECO LIKE '%RJ';

SELECT NOME, SEXO, ENDERECO FROM CLIENTE WHERE SEXO = 'F' AND ENDERECO LIKE '%ESTACIO';

/* CONT (*) GROUP BY, PERFORMACE COM OPERADOR LOGICOS */

/* CONTANDO OS REGISTROS DE UMA TABELA */

SELECT COUNT(*) AS "QUANTIDADES DE REGISTORS DA TAB. CLIENTE" FROM CLIENTE;

/* OPERADOR DE GRUPO BY */

SELECT SEXO, COUNT(*) FROM CLIENTE;

SELECT * FROM CLIENTE;

SELECT SEXO, COUNT(*) FROM CLIENTE GROUP BY SEXO;

/* PERFORMACE EM OPERACOES LOGICAS */

/* 1 MILHAO DE REGISTROS PARA CONTAR */

SELECT COUNT(*) FROM CLIENTE;

SELECT SEXO, COUNT(*) FROM CLIENTE GROUP BY SEXO;

SELECT ENDERECO, COUNT(*) FROM CLIENTE GROUP BY ENDERECO;

/* CONDICAO 
SEXO = F
CIDADE = RIO DE JANEIRO 

SITUACAO - TRATANDO COM OU / OR 
70% MULHER = SEXO = F 
30% MORA NO RIO DE JANEIRO */ 

SELECT NOME, SEXO, ENDERECO FROM CLIENTE WHERE ENDERECO = 'RIO DE JANEIRO' AND SEXO = 'F';

/* EXERCICIO */

/* CONSIDERANDO O QUE VOCE APRENDEU SOBRE PERFORMACE, RESOLVA OS EXERCICIOS ABAIXO */

SELECT COUNT(*) FROM FUNCIONARIOS;

--TRAGA OS FUNCIONARIOS QUE TRABALHEM
--NO DEPARTAMENTO DE FILMES OU NO
--DEPARTAMENTOS DE ROUPAS

-- 21 | FILMES 53 | ROUPAS

--COMO ESTAMOS TRABALHANDO COM OR E A SEGUNDA OPCIONAL
--COLOCAMOS NA PRIMEIRA CONDICAO QUEM TEM MAIS CHANCES DE UMA SAIDA
--VERDADEIRA, POIS A SEGUNDA CONDICAO NAO SERA CHECADA NESSE CASO.

SELECT * FROM FUNCIONARIOS  WHERE DEPARTAMENTO = 'ROUPAS' OR DEPARTAMENTO = 'FILMES';

SELECT COUNT(*), DEPARTAMENTO FROM FUNCIONARIOS GROUP BY DEPARTAMENTOS ORDER BY 1;

WHERE DEPARTAMENTOS = 'FILMES' OR DEPARTAMENTOS = 'ROUPAS' 

--O GESTOR DE MARKETING PEDIU A LISTA DAS FUNCIONARIAS (AS) = FEMININO E QUE TRABALHE NO DEPARTAMENTO
--DE FILMES OU NO DEPARTAMENTO LA. ELE NECESITA ENVIAR UM EMAIL PARA AS COLABORADORAS
--DESSES DOIS SETORES. OR + AND *

--FEMININO 491 OCORENCIAS

SELECT COUNT(*), SEXO FROM FUNCIONARIOS GROUP BY SEXO;

--52 | LAR 21 FILMES

SELECT COUNT(*), DEPARTAMENTO FROM FUNCIONARIOS GROUP BY DEPARTAMENTO;

SELECT * FROM FUNCIONARIOS WHERE (DEPARTAMENTO = 'LAR' AND SEXO = 'FEMININO');

--TRAGA OS FUNCIONARIOS DO SEXO MASCULINO 
--OU OS FUNCIONARIOS QUE TRABALHEM NO SETOR JARDIM 

SELECT * FROM FUNCIONARIOS WHERE SEXO = 'MASCULINO' OR DEPARTAMENTO = 'JARDIM';

CREATE DATABASE EXERCICIO;

USE EXERCICIO;

CREATE TABLE FUNCIONARIOS
(
	IDFUNCIONARIO INTEGER,
	NOME VARCHAR(100),
	EMAIL VARCHAR(200),
	SEXO VARCHAR(10),
	DEPARTAMENTO VARCHAR(100),
	ADMISSAO VARCHAR(10),
	SALARIO INTEGER,
	CARGO VARCHAR(100),
	IDREGIAO INT
);

/* FILTRA VALORES NULOS */

SELECT NOME, SEXO, ENDERECO FROM CLIENTE WHERE SEXO = 'F';

SELECT NOME, SEXO, ENDERECO FROM CLIENTE WHERE EMAIL = NULL;

SELECT NOME, SEXO, EMAIL, ENDERECO FROM CLIENTE WHERE EMAIL IS NULL;

SELECT NOME, SEXO, EMAIL, ENDERECO FROM CLIENTE WHERE EMAIL IS NOT NULL;

/* IS OU IS NOT NULL */

/* UTILIZAR O UPDATE PARA ATUALIZAR VALORES */

SELECT NOME, EMAIL FROM CLIENTE;

UPDATE CLIENTE SET EMAIL = 'LILIAN@HOTMAIL.COM';

SELECT NOME, EMAIL FROM CLIENTE;

/* WHERE - VAI SER SEU MELHOR AMIGO DA VIDA INTEIRA */

SELECT * FROM CLIENTE WHERE NOME = 'LILIAN';

UPDATE CLIENTE SET EMAIL = 'JOAO@IG.COM.BR' WHERE NOME = 'JOAO';

SELECT NOME, EMAIL FROM CLIENTE;

UPDATE CLIENTE SET EMAIL = 'JORGE@IG.COM.BR' WHERE NOME = 'JORGE';

SELECT NOME, EMAIL FROM CLIENTE;

UPDATE CLIENTE SET EMAIL = 'CELIA@HOTMAIL.COM' WHERE NOME = 'CELIA';

SELECT NOME, EMAIL FROM CLIENTE;

UPDATE CLIENTE SET EMAIL = 'ANA@HOTMAIL.COM.' WHERE NOME = 'ANA';

SELECT NOME, EMAIL FROM CLIENTE;

UPDATE CLIENTE SET EMAIL = 'CARLA@HOTMAIL.COM.' WHERE NOME = 'CARLA';

SELECT NOME, EMAIL FROM CLIENTE;

/* COMMIT E ROLLBACK */

/* DELETANDO REGISTROS COM A CLAUSULA DELETE */

DELETE FROM CLIENTE;

SELECT * FROM CLIENTE WHERE NOME = 'ANA';

SELECT COUNT(*) FROM CLIENTE; --TOTAL 6

SELECT COUNT(*) FROM CLIENTE WHERE NOME = 'ANA'; --TOTAL 1

DELETE FROM CLIENTE WHERE NOME = 'ANA';

SELECT COUNT(*) FROM CLIENTE; --RESTANTE 5

SELECT 6 - 1;

SELECT * FROM CLIENTE;

INSERT INTO CLIENTE VALUES('CARLA','F','C.LOPES@UOL.COM',45165468,'5489-0048','RUA COPPER LEAF - WILLIAMSBURG - KITCHENER');

SELECT * FROM CLIENTE;

DELETE FROM CLIENTE WHERE NOME = 'CARLA' OR EMAIL = 'CARLA@HOTMAIL.COM';

SELECT * FROM CLIENTE WHERE NOME = 'CARLA' OR EMAIL = 'CARLA@HOTMAIL.COM';

SELECT * FROM CLIENTE WHERE NOME = 'CARLA' AND EMAIL = 'CARLA@HOTMAIL.COM.'; --OR TRAZ TODO MUNDO COM PELOMENS 1 DAS 2 CONDICOES

DELETE FROM CLIENTE WHERE NOME = 'CARLA' AND EMAIL = 'CARLA@HOTMAIL.COM.'; --AND TRAZ APENAS O REGISTRO QUE SATISFACA AS 2 CONDICOES

SELECT * FROM CLIENTE;

/* ENTRADAS COM MAIS TELEFONES */

UPDATE CLIENTE SET TELEFONE = '97865434' WHERE NOME = 'JOAO';

SELECT * FROM CLIENTE;

UPDATE CLIENTE SET TELEFONE = '22923110 - 97865434' WHERE NOME = 'JOAO';

SELECT * FROM CLIENTE;

SELECT SEXO, COUNT(*) FROM CLIENTE GROUP BY SEXO;

SELECT ENDERECO, COUNT(*) FROM CLIENTE GROUP BY ENDERECO;

/* HISTORIA DA MODELAGEM 

DECADA DE 70, EUA - CRISE DO SOFTWARE
FOI A CRISE QUE ATINGIU NAO SOMENTE A AREA DE TECNOLOGIA
MAS TAMBÉM TODAS AS EMPRESAS QUE UTILIZAVAM DE SISTEMAS
TECNOLOGICOS PARA CONTROLAR SEUS NEGOCIOS.

NAQUELA EPOCA, PROGRAMAR ERA UM PROCESSO ARTESANAL.
BASTAVA OLHAR O CODIGO QUE VOCE SABERIA QUEM O
ESCREVEU, TAO POUCOS ERAM OS PROGRAMADORES EACHTAO ARCAICO ERAM
OS METODOS DE PROGRAMACAO. EM UM PRIMEIRO MOMENTO,
OS PROFISSIONAIS DE TI VIRAM A NECESSIDADE DE SE PROGRAMAR
E INICIARAM SUA CAMINHADA, CONSTRUINDO SISTEMAS QUE ATENDIAM
NUM PRIMEIRO MOMENTO, MAS DEPOIS TRAZIAM INFORMACOES ERRADAS,
PROVOCANDO A FALENCIA DE DIVERSAS EMPRESAS. LEMBRE-SE: INFORMACOES
ERRADAS PODEM LEVAR A SUA EMPRESA A FALENCIA, E FOI ISSO QUE ACONTECEU.
ISSO OCORRIA POIS OS PROFISSIONAIS SABIAM PROGRAMAR MAS ENTENDIAM APENAS
DO NEGOCIO DAS EMPRESAS DAS QUAIS FAZIAM PARTE. SER TER O KNOW HOW
DOS DEMAIS NEGOCIOS, OS PROGRAMADORES PROGRAMAVAM VOLTADOS PARA OS
PROCEDIMENTOS, E ESSE FOI UM ERRO MORTAL.

PETER CHEN, VENDO TODO ESSE CENARIO AFIRMOU: NAO PODEMOS CRIAR BANCOS
DE DADOS VOLTADOS PARA PROCEDIMENTOS EMPRESARIAIS, POIS OS PROCEDIMENTOS
SOFREM INTERFERENCIAS EXTERNAS E PODEM SER ALTERADOS. A UNICA COISA
QUE NAO SOFRE ALTERACAO SAO OS DADOS.

POR EXEMPLO, ARMAZENAMOS NO BANCO A VENDA DE JANEIRO, FEVEREIRO E MARCO
O TOTAL DAS VENDAS E O IMPOSTO PAGO AO GOVERNO. 
FAZEMOS ISSO DURANTE MUITO TEMPO. DE UMA HORA PRA OUTRA O GOVERNO
MUDA A ALIQUOTA DO IMPOSTO. COMO FARÁ SENTIDO OS PAGAMENTOS ARMAZENADOS
ANTERIORMENTE? AQUI NOTA-SE QUE ARMAZENAMOS DADOS E ARMAZENAMOS
INFORMACOES CORRESPONDENTES AOS PROCEDIMENTOS EXTERNOS. DEVEMOS
APENAS ARMAZENAR OS DADOS, POIS ELES SAO SUFICIENTES PARA GERAR
A INFORMACAO.

MODELAR É UMA ARTE, ALGO QUE SE APRENDE COM A PRATICA. E VOCES PODEM
SE PERGUNTAR: MAS SE É ALGO QUE SE APRENDE COM A PRATICA, COMO QUEM
ESTA COMEÇANDO, APRENDE?

ASSIM COMO PETER CHEN CRIOU O MODELO DE ENTIDADE E RELACIONAMENTO, O MER,
FORAM CRIADAS FORMAS NORMAIS, QUE SAO DIRETRIZES PARA APLICAR EM
MODELAGEM DE AMBIENTES OLTP OU AMBIENTES TRANSACIONAIS DE BANCOS
DE DADOS.

HOJE TEMOS MAIS DO QUE 3 FORMAS NORMAIS, MAS AO NORMALIZARMOS UM
BANCO ATE A SUA TERCEIRA FORMA, É O SUFICIENTE PARA TER UM
TRABALHO LIMPO E LIVRE DE ERROS. VEREMOS AS TRES FORMAS NORMAIS,
UMA A UMA, DETALHADAMENTE NAS PROXIMAS AULAS.
*/

INSERT INTO CLIENTE VALUES('CARLA','F','C.LOPES@UOL.COM',45638854,'9301-7585','RUA COPPER LEAF - WILLIAMBURG - KITCHENER');

SELECT SEXO, COUNT(*) AS QTD FROM CLIENTE GROUP BY SEXO;

/* PRIMEIRA FORMA NORMAL */

/*

1 - TODO O CAMPO VETORIZADO SE TORNAR A OUTRA TABELA 

[AMARELO, AZUL, LARANJA, VERDE] -> CORES
[KA, FIESTA, UNO, CIVIC] -> CARROS

2 - TODO O CAMPO MULTIVALORADO SE TORNA A OUTRA TABELA. 
QUANDO O CAMPO FOR DIVISIVEL

3 - TODA A TABELA NECESSITA DE PELOMENOS UM CAMPO IDENTIFIQUE TODO O REGISTRO COMO SENDO UNICO.
ISSO E O QUE CHAMAMOS DE CHAVE PRIMARIA OU PRIMARY KEY.

*/

/* CADINALIDADE */

/*QUEM DEFINE A CADINALIDADE E A REGRA DE NEGOCIOS */

/*PRIMEIRO ALGARISMO - OBRIGATORIEDADE
0 - NAO OBRIGATORIO
1 - OBRIGATORIO

SEGUNDA ALGARISMO - CARDINALIDADE 
1 - MAXIMA DE 1
N - MAS DE 1
*/

CREATE DATABASE COMERCIO;

USE COMERCIO;

SHOW DATABASES; --> OPCIONAL

DROP TABLE CLIENTE;

CREATE TABLE CLIENTE(
	IDCLIENTE INT PRIMARY KEY AUTO_INCREMENT,
	NOME VARCHAR(30) NOT NULL,
	SEXO ENUM('M','F') NOT NULL,
	EMAIL VARCHAR(50) UNIQUE,
	CPF VARCHAR(15) UNIQUE
);

CREATE TABLE ENDERECO(
	IDENDERECO INT PRIMARY KEY AUTO_INCREMENT,
	RUA VARCHAR(30) NOT NULL,
	BAIRRO VARCHAR(30) NOT NULL,
	CIDADE VARCHAR(30) NOT NULL,
	ESTADO CHAR(2) NOT NULL,
	ID_CLIENTE INT UNIQUE,
	
	FOREIGN KEY(ID_CLIENTE)
	REFERENCES CLIENTE(IDCLIENTE)
);

CREATE TABLE TELEFONE(
	IDTELEFONE INT PRIMARY KEY AUTO_INCREMENT,
	TIPO ENUM('RES','COM','CEL') NOT NULL,
	NUMERO VARCHAR(10) NOT NULL,
	ID_CLIENTE INT,
	
	FOREIGN KEY (ID_CLIENTE)
	REFERENCES CLIENTE(IDCLIENTE)
);

/*ENDERECO - OBRIGATORIO CADASTRO DE SOMENTE 1.

TELEFONE - NAO OBRIGATORIO CADASTRO DE MAS DE 1 (OPCIONAL) */

/* CHAVE ESTRANGEIRA E CHAVE PRIMARIA DE UMA TABELA QUE VAI ATE A OUTRA TABELA PARA FAZER REFERENCIA ENTRE REGISTROS */

/* EM RELACIONAMENTOS 1 X 1 A CHAVE ESTRANGEIRA FICA NA TABELA MAIS FRACA */

/* EM RELACIONAMENTO DE 1 X N A CHAVE ESTRANGEIRA FICA SEMPRE NA CARDINALIDADE N */

DESC CLIENTE;

INSERT INTO CLIENTE VALUES(NULL,'JOAO','M','JOAO@IG.COM','52145604');

INSERT INTO CLIENTE VALUES(NULL,'CARLOS','M','CARLOS@IG.COM','54844184');

INSERT INTO CLIENTE VALUES(NULL,'ANA','F','ANA@IG.COM','54846546');

INSERT INTO CLIENTE VALUES(NULL,'CLARA','F',NULL,'54864651');

INSERT INTO CLIENTE VALUES(NULL,'JORGE','M','JORGE@IG.COM','54846816');

INSERT INTO CLIENTE VALUES(NULL,'CELIA','M','JCELIA@IG.COM','56484984');

SELECT * FROM CLIENTE;

+-----------+--------+------+---------------+----------+
| IDCLIENTE | NOME   | SEXO | EMAIL         | CPF      |
+-----------+--------+------+---------------+----------+
|         1 | JOAO   | M    | JOAO@IG.COM   | 52145604 |
|         2 | CARLOS | M    | CARLOS@IG.COM | 54844184 |
|         3 | ANA    | F    | ANA@IG.COM    | 54846546 |
|         4 | CLARA  | F    | NULL          | 54864651 |
|         5 | JORGE  | M    | JORGE@IG.COM  | 54846816 |
|         6 | CELIA  | M    | JCELIA@IG.COM | 56484984 |
+-----------+--------+------+---------------+----------+

DESC ENDERECO;

INSERT INTO ENDERECO VALUES(NULL,'RUA ANTONIO SA','CENTRO','B.HORIZONTE','MG',4);

INSERT INTO ENDERECO VALUES(NULL,'RUA CAPITAO HERMES','CENTRO','RIO DE JANEIRO','RJ',1);

INSERT INTO ENDERECO VALUES(NULL,'RUA PRES VAGAS','JARDINS','SAO PAULO','SP',3);

INSERT INTO ENDERECO VALUES(NULL,'RUA ALFANDEGA','ESTACIO','RIO DE JANEIRO','RJ',2);

INSERT INTO ENDERECO VALUES(NULL,'RUA DO OUVIDOR','FLAMENGO','RIO DE JANEIRO','RJ',6);

INSERT INTO ENDERECO VALUES(NULL,'RUA URUGUAIANA','CENTRO','VITORIA','ES',5);

INSERT INTO ENDERECO VALUES(NULL,'RUA ALFANDEGA','CENTRO','SAO PAULO','SP',5);

SELECT * FROM ENDERECO;

DESC TELEFONE;

INSERT INTO TELEFONE VALUES (NULL,'CEL','5484-1810',5);

INSERT INTO TELEFONE VALUES (NULL,'RES','8285-3852',5);

INSERT INTO TELEFONE VALUES (NULL,'CEL','9291-2923',1);

INSERT INTO TELEFONE VALUES (NULL,'COM','8419-2968',2);

INSERT INTO TELEFONE VALUES (NULL,'RES','9634-1981',1);

INSERT INTO TELEFONE VALUES (NULL,'CEL','8287-1953',3);

INSERT INTO TELEFONE VALUES (NULL,'CEL','8129-8126',3);

INSERT INTO TELEFONE VALUES (NULL,'COM','5985-1415',1);

INSERT INTO TELEFONE VALUES (NULL,'COM','3518-6448',5);

INSERT INTO TELEFONE VALUES (NULL,'CEL','7896-5416',2);

SELECT * FROM TELEFONE;

/* SELECAO, PROJECAO E JUNCAO */

/* PROJECAO -> E TUDO O QUE VOCE QUER VER NA TELA */

SELECT NOW() AS DATA_ATUAL;

SELECT 2 + 2 AS SOMA;

SELECT 2 = 2 AS SOMA, NOME, NOW() FROM CLIENTE;

/* SELECAO - > E UM SUBCONJUNTO DO CONJUNTO DE REGISTRO DE UMA TABELA 
A CLAUSULA DE SELECAO E O WHERE */

SELECT NOME, SEXO, EMAIL FROM CLIENTE WHERE SEXO = 'F';

SELECT NOME, SEXO, EMAIL --PROJECAO
FROM CLIENTE --ORIGEM
WHERE SEXO = 'F' -- SELECAO

SELECT NUMERO FROM TELEFONE WHERE TIPO = 'CEL';

SELECT NUMERO --PROJECAO
FROM TELEFONE --ORIGEM
WHERE TIPO = 'CEL' --SELECAO

/* JUNCAO -> JOIN */

SELECT NOME, EMAIL, IDCLIENTE FROM CLIENTE;

SELECT ID_CLIENTE, BAIRRO, CIDADE FROM ENDERECO;

+--------+---------------+-----------++------------+----------+----------------+
| NOME   | EMAIL         | IDCLIENTE || ID_CLIENTE | BAIRRO   | CIDADE         |
+--------+---------------+-----------++------------+----------+----------------+
| JOAO   | JOAO@IG.COM   |         1 ||          1 | CENTRO   | RIO DE JANEIRO |
| CARLOS | CARLOS@IG.COM |         2 ||          2 | ESTACIO  | RIO DE JANEIRO |
| ANA    | ANA@IG.COM    |         3 ||          3 | JARDINS  | SAO PAULO      |
| CLARA  | NULL          |         4 ||          4 | CENTRO   | B.HORIZONTE    |
| JORGE  | JORGE@IG.COM  |         5 ||          5 | CENTRO   | VITORIA        |
| CELIA  | JCELIA@IG.COM |         6 ||          6 | FLAMENGO | RIO DE JANEIRO |
+--------+---------------+-----------++------------+----------+----------------+

/* NOME, SEXO, BAIRRO, CIDADE */

SELECT NOME, SEXO, BAIRRO, CIDADE FROM CLIENTE, ENDERECO WHERE IDCLIENTE = ID_CLIENTE;

SELECT NOME, SEXO, BAIRRO, CIDADE --PROJECAO 
FROM CLIENTE, ENDERECO --ORIGEM
WHERE IDCLIENTE = ID_CLIENTE --JUNCAO

+--------+------+----------+----------------+
| NOME   | SEXO | BAIRRO   | CIDADE         |
+--------+------+----------+----------------+
| JOAO   | M    | CENTRO   | RIO DE JANEIRO |
| CARLOS | M    | ESTACIO  | RIO DE JANEIRO |
| ANA    | F    | JARDINS  | SAO PAULO      |
| CLARA  | F    | CENTRO   | B.HORIZONTE    |
| JORGE  | M    | CENTRO   | VITORIA        |
| CELIA  | M    | FLAMENGO | RIO DE JANEIRO |
+--------+------+----------+----------------+

/* WHERE = SELECAO */

SELECT NOME, SEXO, BAIRRO, CIDADE FROM CLIENTE, ENDERECO WHERE IDCLIENTE = ID_CLIENTE AND SEXO = 'F';

+-------+------+---------+-------------+
| NOME  | SEXO | BAIRRO  | CIDADE      |
+-------+------+---------+-------------+
| ANA   | F    | JARDINS | SAO PAULO   |
| CLARA | F    | CENTRO  | B.HORIZONTE |
+-------+------+---------+-------------+

/* HERE IDCLIENTE = ID_CLIENTE 
AND SEXO = 'F' = TABELA VERDADE */

INSERT INTO ENDERECO VALUES(NULL,'RUA ANTONIO SA','CENTRO','B.HORIZONTE','MG',15);

SELECT NOME, SEXO, BAIRRO, CIDADE 
FROM CLIENTE 
INNER JOIN ENDERECO ON IDCLIENTE = ID_CLIENTE;

+--------+------+----------+----------------+
| NOME   | SEXO | BAIRRO   | CIDADE         |
+--------+------+----------+----------------+
| JOAO   | M    | CENTRO   | RIO DE JANEIRO |
| CARLOS | M    | ESTACIO  | RIO DE JANEIRO |
| ANA    | F    | JARDINS  | SAO PAULO      |
| CLARA  | F    | CENTRO   | B.HORIZONTE    |
| JORGE  | M    | CENTRO   | VITORIA        |
| CELIA  | M    | FLAMENGO | RIO DE JANEIRO |
+--------+------+----------+----------------+

SELECT NOME, SEXO, BAIRRO, CIDADE FROM CLIENTE INNER JOIN ENDERECO ON IDCLIENTE = ID_CLIENTE WHERE SEXO ='F';

SELECT NOME, SEXO, BAIRRO, CIDADE --PROJECAO
FROM CLIENTE --ORIGEM
	INNER JOIN ENDERECO --JUNCAO
	ON IDCLIENTE = ID_CLIENTE
WHERE SEXO ='F'; --SELECAO

/* NOME, SEXO, EMAIL ,TIPO, NUMERO */

SELECT NOME, SEXO, EMAIL, TIPO, NUMERO FROM CLIENTE INNER JOIN TELEFONE ON IDCLIENTE = ID_CLIENTE;

/* NOME, SEXO, BAIRRO, CIDADE, TIPO, NUMERO */

SELECT CLIENTE.NOME, CLIENTE.SEXO, ENDERECO.BAIRRO, ENDERECO.CIDADE, TELEFONE.TIPO, TELEFONE.NUMERO FROM CLIENTE INNER JOIN ENDERECO ON CLIENTE.IDCLIENTE = ENDERECO.ID_CLIENTE INNER JOIN TELEFONE ON CLIENTE.IDCLIENTE = TELEFONE.ID_CLIENTE;

+--------+------+---------+----------------+------+-----------+
| NOME   | SEXO | BAIRRO  | CIDADE         | TIPO | NUMERO    |
+--------+------+---------+----------------+------+-----------+
| JOAO   | M    | CENTRO  | RIO DE JANEIRO | CEL  | 9291-2923 |
| JOAO   | M    | CENTRO  | RIO DE JANEIRO | RES  | 9634-1981 |
| JOAO   | M    | CENTRO  | RIO DE JANEIRO | COM  | 5985-1415 |
| CARLOS | M    | ESTACIO | RIO DE JANEIRO | COM  | 8419-2968 |
| CARLOS | M    | ESTACIO | RIO DE JANEIRO | CEL  | 7896-5416 |
| ANA    | F    | JARDINS | SAO PAULO      | CEL  | 8287-1953 |
| ANA    | F    | JARDINS | SAO PAULO      | CEL  | 8129-8126 |
| JORGE  | M    | CENTRO  | VITORIA        | CEL  | 5484-1810 |
| JORGE  | M    | CENTRO  | VITORIA        | RES  | 8285-3852 |
| JORGE  | M    | CENTRO  | VITORIA        | COM  | 3518-6448 |
+--------+------+---------+----------------+------+-----------+

SELECT CLIENTE.NOME, CLIENTE.SEXO, ENDERECO.BAIRRO, ENDERECO.CIDADE, TELEFONE.TIPO, TELEFONE.NUMERO FROM CLIENTE INNER JOIN ENDERECO ON CLIENTE.IDCLIENTE = ENDERECO.ID_CLIENTE INNER JOIN TELEFONE ON CLIENTE.IDCLIENTE = TELEFONE.ID_CLIENTE;

+--------+------+---------+----------------+------+-----------+
| NOME   | SEXO | BAIRRO  | CIDADE         | TIPO | NUMERO    |
+--------+------+---------+----------------+------+-----------+
| JOAO   | M    | CENTRO  | RIO DE JANEIRO | CEL  | 9291-2923 |
| JOAO   | M    | CENTRO  | RIO DE JANEIRO | RES  | 9634-1981 |
| JOAO   | M    | CENTRO  | RIO DE JANEIRO | COM  | 5985-1415 |
| CARLOS | M    | ESTACIO | RIO DE JANEIRO | COM  | 8419-2968 |
| CARLOS | M    | ESTACIO | RIO DE JANEIRO | CEL  | 7896-5416 |
| ANA    | F    | JARDINS | SAO PAULO      | CEL  | 8287-1953 |
| ANA    | F    | JARDINS | SAO PAULO      | CEL  | 8129-8126 |
| JORGE  | M    | CENTRO  | VITORIA        | CEL  | 5484-1810 |
| JORGE  | M    | CENTRO  | VITORIA        | RES  | 8285-3852 |
| JORGE  | M    | CENTRO  | VITORIA        | COM  | 3518-6448 |
+--------+------+---------+----------------+------+-----------+

/*
		DML - DATA MANIPULATION LANGUAGE
		DDL - DATA DEFINITION LANGUAGE
		DCL - DATA CONTROLE LANGUAGE
		TCL - TRANSACTION CONTROL LANGUAGE
*/

/* INSERT */

INSERT INTO CLIENTE VALUES(NULL,'PAULA','M',NULL,'44352186');
INSERT INTO ENDERECO VALUES(NULL,'RUA JOAQUIM SILVA','ALVORADA','NITEROI','RJ',7);

SELECT * FROM CLIENTE;

/* FILTRO */

SELECT * FROM CLIENTE WHERE SEXO = 'M';

/* UPDATE */

SELECT * FROM CLIENTE WHERE IDCLIENTE = 7;

UPDATE CLIENTE SET SEXO = 'F' WHERE IDCLIENTE =7;

/* DELETE */

INSERT INTO CLIENTE VALUES(NULL,'XXX','M',NULL,'XXX');

SELECT * FROM CLIENTE WHERE IDCLIENTE = 8;

DELETE FROM CLIENTE WHERE IDCLIENTE = 8;

/* DDL - DATA DEFINITION LANGUAGE */

CREATE TABLE PRODUTO(
	IDPRODUTO INT PRIMARY KEY AUTO_INCREMENT,
	NOME_PRODUTO VARCHAR(30) NOT NULL,
	PRECO INT,
	FRETE FLOAT(10,2) NOT NULL
);

/* ALTER TABELA */

/* ALTERA O NOME DE UMA COLUNA - CHANGE */

ALTER TABLE PRODUTO CHANGE PRECO VALOR_UNITARIO INT NOT NULL;

DESC PRODUTO;
+----------------+-------------+------+-----+---------+----------------+
| Field          | Type        | Null | Key | Default | Extra          |
+----------------+-------------+------+-----+---------+----------------+
| IDPRODUTO      | int(11)     | NO   | PRI | NULL    | auto_increment |
| NOME_PRODUTO   | varchar(30) | NO   |     | NULL    |                |
| VALOR_UNITARIO | int(11)     | NO   |     | NULL    |                |
| FRETE          | float(10,2) | NO   |     | NULL    |                |
+----------------+-------------+------+-----+---------+----------------+

ALTER TABLE PRODUTO CHANGE VALOR_UNITARIO VALOR_UNITARIO INT;

DESC PRODUTO
+----------------+-------------+------+-----+---------+----------------+
| Field          | Type        | Null | Key | Default | Extra          |
+----------------+-------------+------+-----+---------+----------------+
| IDPRODUTO      | int(11)     | NO   | PRI | NULL    | auto_increment |
| NOME_PRODUTO   | varchar(30) | NO   |     | NULL    |                |
| VALOR_UNITARIO | int(11)     | YES  |     | NULL    |                |
| FRETE          | float(10,2) | NO   |     | NULL    |                |
+----------------+-------------+------+-----+---------+----------------+

/* APAGANDO TABELA */

DROP TABLE PRODUTO;

/* MODIFY - ALTERANDO O TIPO */

ALTER TABLE PRODUTO MODIFY VALOR_UNITARIO VARCHAR(50) NOT NULL;

/* ADICIONANDO COLUNAS */

ALTER TABLE PRODUTO ADD COLUMN PESO FLOAT(10,2) NOT NULL AFTER;

/* APAGANDO UMA COLUNA */

ALTER TABLE PRODUTO DROP COLUMN PESO;

/* ADICIONAMDO UMA COLUNA NA ORDEM ESPECIFICA */

ALTER TABLE PRODUTO ADD COLUMN PESO FLOAT(10,2) NOT NULL AFTER NOME_PRODUTO;

ALTER TABLE PRODUTO DROP COLUMN PESO;

ALTER TABLE PRODUTO ADD COLUMN PESO FLOAT(10,2) NOT NULL FIRST;

*/ EXERCICIOS DML */

INSERT INTO CLIENTE VALUES(NULL,'FLAVIO','M','FLAVIO@IG.COM','346.846.321-68');
INSERT INTO CLIENTE VALUES(NULL,'ANDRE','M','ANDRE@GLOBO.COM','289.216.489-64');
INSERT INTO CLIENTE VALUES(NULL,'GIOVANA','F',NULL,'368.743.388-73');
INSERT INTO CLIENTE VALUES(NULL,'KARLA','F','KARLA@GMAIL.COM','764.483.468-28');
INSERT INTO CLIENTE VALUES(NULL,'DANIELE','M','DANIELE@GMAIL.COM','697.621.843-28');
INSERT INTO CLIENTE VALUES(NULL,'LORENA','M',NULL,'646.218.132-18');
INSERT INTO CLIENTE VALUES(NULL,'EDUARDO','M',NULL,'982.189.746-18');
INSERT INTO CLIENTE VALUES(NULL,'ANTONIO','F','ANTONIO@IG.COM','284.654.876-51');
INSERT INTO CLIENTE VALUES(NULL,'ANTONIO','M','ANTONIO@UOL.COM','397.541.432-86');
INSERT INTO CLIENTE VALUES(NULL,'ELAINE','M','ELAINE@GLOBO','687.463.218-76');
INSERT INTO CLIENTE VALUES(NULL,'CARMEM','M','CARMEM@IG.COM','786.465.464-31');
INSERT INTO CLIENTE VALUES(NULL,'ADRIANA','F','ADRIANA@GMAIL.COM','843.521.845-18');
INSERT INTO CLIENTE VALUES(NULL,'JOICE','F','JOICE@GMAIL.COM','861.354.843-21');


/* CADASTRA UM ENDERECO PARA CADA CLIENTE */

INSERT INTO ENDERECO VALUES(NULL,);
INSERT INTO ENDERECO VALUES(NULL,);
INSERT INTO ENDERECO VALUES(NULL,);
INSERT INTO ENDERECO VALUES(NULL,);
INSERT INTO ENDERECO VALUES(NULL,);
INSERT INTO ENDERECO VALUES(NULL,);
INSERT INTO ENDERECO VALUES(NULL,);
INSERT INTO ENDERECO VALUES(NULL,);
INSERT INTO ENDERECO VALUES(NULL,);
INSERT INTO ENDERECO VALUES(NULL,);
INSERT INTO ENDERECO VALUES(NULL,);
INSERT INTO ENDERECO VALUES(NULL,);
INSERT INTO ENDERECO VALUES(NULL,);

/* CADASTRA TELEFONE PARA OS CLIENTES */

INSERT INTO TELEFONE VALUES(NULL,);
INSERT INTO TELEFONE VALUES(NULL,);
INSERT INTO TELEFONE VALUES(NULL,);
INSERT INTO TELEFONE VALUES(NULL,);
INSERT INTO TELEFONE VALUES(NULL,);
INSERT INTO TELEFONE VALUES(NULL,);
INSERT INTO TELEFONE VALUES(NULL,);
INSERT INTO TELEFONE VALUES(NULL,);
INSERT INTO TELEFONE VALUES(NULL,);
INSERT INTO TELEFONE VALUES(NULL,);
INSERT INTO TELEFONE VALUES(NULL,);
INSERT INTO TELEFONE VALUES(NULL,);
INSERT INTO TELEFONE VALUES(NULL,);
